url=jdbc:postgresql://localhost:5432/DEALBOARD_DB
referenceUrl=hibernate:spring:com.td.dealboard?dialect=org.hibernate.dialect.PostgreSQLDialect
referenceDriver=liquibase.ext.hibernate.database.connection.HibernateDriver
username=admin
password=adminpassword
changeLogFile=src/main/resources/db/changelog/db.changelog-master.yaml
driver=org.postgresql.Driver
