spring.application.name=dealboard
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.database=postgresql

server.port = 8082

app.oauth2.redirect-uri="http://localhost:3000/oauth2/success"
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri=http://10.0.2.2:8081/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=email,profile

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo


my.scraper.cron=0 0 4 * * *
my.scraper.zone=Europe/Warsaw
my.scraper.base-dir=data/pdf

scrapper.ai.batch-size: 5
scrapper.ai.max-tokens: 4120
scrapper.ai.parallelism: 8
scrapper.ai.rate-limit: 4500

app.categories.path=/categories.csv